services:
  socks-server:
    image: "registry.cn-shanghai.aliyuncs.com/iproute/netty-server-socks:latest"
    container_name: "netty-server-socks"
    network_mode: host
    volumes:
      - "./logs:/opt/app/logs"
    environment:
      - JAVA_OPTIONS=-Xms128M -Xmx128M
      - TZ=Asia/Shanghai
